### Pivot Tables in Pandas -> Used to Summarize and Aggregate Data inside a Dataframe

In [1]:
# Concept of Pivot Tables:- A Pivot Table is essentially a tool that turns "long" data into "wide" data. It allows you to take a messy list of records and summarize them into a clean, 2-dimensional grid.
# Think of it as a three-way intersection: you pick one column to be your Rows, another to be your Columns, and a third to be the Values (the numbers in the middle).

# #pivot_df = df.pivot_table(
#     values='salary_year_avg',   # What numbers are we calculating?
#     index='job_title_short',    # What goes on the left (Rows)?
#     columns='job_country',      # What goes on the top (Columns)?
#     aggfunc='mean'              # How do we combine data? (mean, median, sum, count)

In [ ]:
# Main Usage of Pivot tables come when we have multiple entries for a Single Intersection of index
# and column. For example, On the Same Date, a City can have multiple values of Temp and Humidity.
# If we use simple pivoting here, Pandas doesn't know which entry to choose between the 2, 
# and throws a "Index contains duplicate entries, cannot reshape" Error. 

# But if we use pivot_table() here, Pandas will know with the help of our Aggregate function, that
# what should be done with those multiple values to aggregate them into a single value.


# Use pivot_table whenever:
# 1. There is "Noise": You have multiple sensors or multiple timestamps for the same category.

# 2. You want a Summary: You don't care about the individual 10 AM and 4 PM readings; you just want the Daily Average or the Daily Maximum.

# 3. Data is messy: Real-world data almost always has duplicates. Using pivot_table is "defensive coding"—it prevents your app from crashing if a duplicate row accidentally sneaks into your CSV.

![alt text](<Screenshot 2025-12-25 094923.png>)

In [ ]:
# If we don't provide a aggregate function, mean() is used to calculate the avg of multiple values and 
# Fill the value.
import pandas as pd


weather_data = [
    # --- May 1st ---
    {"date": "2025-05-01", "city": "Kolkata", "temp": 30, "humidity": 85},      # Morning
    {"date": "2025-05-01", "city": "Kolkata", "temp": 36, "humidity": 70},      # Afternoon
    {"date": "2025-05-01", "city": "Bankura", "temp": 38, "humidity": 45},
    {"date": "2025-05-01", "city": "Bankura", "temp": 44, "humidity": 28},
    {"date": "2025-05-01", "city": "Bhubaneswar", "temp": 31, "humidity": 75},
    {"date": "2025-05-01", "city": "Bhubaneswar", "temp": 37, "humidity": 68},
    {"date": "2025-05-01", "city": "Patna", "temp": 34, "humidity": 42},
    {"date": "2025-05-01", "city": "Patna", "temp": 41, "humidity": 30},
    {"date": "2025-05-01", "city": "Ranchi", "temp": 28, "humidity": 60},
    {"date": "2025-05-01", "city": "Ranchi", "temp": 33, "humidity": 50},
    {"date": "2025-05-01", "city": "Darjeeling", "temp": 15, "humidity": 90},
    {"date": "2025-05-01", "city": "Darjeeling", "temp": 21, "humidity": 75},
    
    # --- May 2nd ---
    {"date": "2025-05-02", "city": "Kolkata", "temp": 31, "humidity": 82},
    {"date": "2025-05-02", "city": "Kolkata", "temp": 35, "humidity": 72},
    {"date": "2025-05-02", "city": "Bankura", "temp": 39, "humidity": 40},
    {"date": "2025-05-02", "city": "Bankura", "temp": 45, "humidity": 25},
    {"date": "2025-05-02", "city": "Bhubaneswar", "temp": 32, "humidity": 72},
    {"date": "2025-05-02", "city": "Bhubaneswar", "temp": 38, "humidity": 65},
    {"date": "2025-05-02", "city": "Patna", "temp": 35, "humidity": 38},
    {"date": "2025-05-02", "city": "Patna", "temp": 42, "humidity": 28},
    {"date": "2025-05-02", "city": "Ranchi", "temp": 29, "humidity": 55},
    {"date": "2025-05-02", "city": "Ranchi", "temp": 34, "humidity": 45},
    {"date": "2025-05-02", "city": "Darjeeling", "temp": 14, "humidity": 92},
    {"date": "2025-05-02", "city": "Darjeeling", "temp": 20, "humidity": 80}
]

df = pd.DataFrame(weather_data)

# df.pivot(index = "city", columns='date') ---> ERROR !

df.pivot_table(index='city', columns='date') # Average values of multiple Temp and Humidity are calculated.

              humidity                  temp
date        2025-05-01 2025-05-02 2025-05-01 2025-05-02
city
Bankura           36.5       32.5       41.0       42.0
Bhubaneswar       71.5       68.5       34.0       35.0
Darjeeling        82.5       86.0       18.0       17.0
Kolkata           77.5       77.0       33.0       33.0
Patna             36.0       33.0       37.5       38.5
Ranchi            55.0       50.0       30.5       31.5

In [ ]:
# Providing our own Aggregate Functions --> MEDIAN()
df.pivot_table(index='city', columns='date', aggfunc='median')

              humidity                  temp
date        2025-05-01 2025-05-02 2025-05-01 2025-05-02
city
Bankura           36.5       32.5       41.0       42.0
Bhubaneswar       71.5       68.5       34.0       35.0
Darjeeling        82.5       86.0       18.0       17.0
Kolkata           77.5       77.0       33.0       33.0
Patna             36.0       33.0       37.5       38.5
Ranchi            55.0       50.0       30.5       31.5

In [9]:
# Providing our own Aggregate Functions --> MAX()
df.pivot_table(index='city', columns='date', aggfunc='max')

              humidity                  temp
date        2025-05-01 2025-05-02 2025-05-01 2025-05-02
city
Bankura             45         40         44         45
Bhubaneswar         75         72         37         38
Darjeeling          90         92         21         20
Kolkata             85         82         36         35
Patna               42         38         41         42
Ranchi              60         55         33         34

In [ ]:
# Providing our own Aggregate Functions --> COUNT() ---> How many different values occur for a particular Column for an Intersection Point of City + Date
df.pivot_table(index='city', columns='date', aggfunc='count')

              humidity                  temp
date        2025-05-01 2025-05-02 2025-05-01 2025-05-02
city
Bankura              2          2          2          2
Bhubaneswar          2          2          2          2
Darjeeling           2          2          2          2
Kolkata              2          2          2          2
Patna                2          2          2          2
Ranchi               2          2          2          2

In [14]:
# Providing our own Aggregate Functions --> COUNT() and also wanting to see only Temp column
# ---> Aggregate(here COUNT()) the different values of "temp" to a single value, for every unique (City + Date) 
# intersection point.
df.pivot_table(index='city', columns='date', values='temp', aggfunc='count')

date         2025-05-01  2025-05-02
city
Bankura               2           2
Bhubaneswar           2           2
Darjeeling            2           2
Kolkata               2           2
Patna                 2           2
Ranchi                2           2

In [19]:
# When you set margins=True, Pandas adds an extra row at the bottom and an extra column on the far  
# right that calculates the Total (or Average, depending on your aggfunc) for that entire row or column.

# 2. What the "All" cells represent
# ➡️ The Bottom Row: Shows the average temperature of all cities combined for each specific date.
# ➡️ The Right Column: Shows the average temperature of all days combined for each specific city.
# ➡️ The Bottom-Right Corner: Shows the "Grand Average"—the mean temperature of the entire dataset.

print(df.pivot_table(index='city', columns='date', values='temp', aggfunc='count', margins=True, margins_name='Total Count'))

df.pivot_table(index='city', columns='date', values=['temp', 'humidity'], aggfunc='mean', margins=True, margins_name='Regional Average')

date         2025-05-01  2025-05-02  Total Count
city
Bankura               2           2            4
Bhubaneswar           2           2            4
Darjeeling            2           2            4
Kolkata               2           2            4
Patna                 2           2            4
Ranchi                2           2            4
Total Count          12          12           24

                   humidity                                   temp             \
date             2025-05-01 2025-05-02 Regional Average 2025-05-01 2025-05-02
city
Bankura           36.500000  32.500000        34.500000  41.000000  42.000000
Bhubaneswar       71.500000  68.500000        70.000000  34.000000  35.000000
Darjeeling        82.500000  86.000000        84.250000  18.000000  17.000000
Kolkata           77.500000  77.000000        77.250000  33.000000  33.000000
Patna             36.000000  33.000000        34.500000  37.500000  38.500000
Ranchi            55.000000  50.000000        52.500000  30.500000  31.500000
Regional Average  59.833333  57.833333        58.833333  32.333333  32.833333


date             Regional Average
city
Bankura                 41.500000
Bhubaneswar             34.500000
Darjeeling              17.500000
Kolkata                 33.000000
Patna                   38.000000
Ranchi                  31.000000
Regional Average        32.583333

In [26]:
# Using Multiple Aggregate Functions
df.pivot_table(index='city', columns='date', values = 'temp', aggfunc=['mean', 'median'], margins=True, margins_name='Grand Statistics') 
# Multiple margin_names not allowed. Something like 'Grand Statistics' works fine !

                       mean                                 median             \
date             2025-05-01 2025-05-02 Grand Statistics 2025-05-01 2025-05-02
city
Bankura           41.000000  42.000000        41.500000       41.0       42.0
Bhubaneswar       34.000000  35.000000        34.500000       34.0       35.0
Darjeeling        18.000000  17.000000        17.500000       18.0       17.0
Kolkata           33.000000  33.000000        33.000000       33.0       33.0
Patna             37.500000  38.500000        38.000000       37.5       38.5
Ranchi            30.500000  31.500000        31.000000       30.5       31.5
Grand Statistics  32.333333  32.833333        32.583333       33.5       34.5


date             Grand Statistics
city
Bankura                      41.5
Bhubaneswar                  34.5
Darjeeling                   17.5
Kolkata                      33.0
Patna                        38.0
Ranchi                       31.0
Grand Statistics             34.0