### Pivoting in Pandas Dataframes -> To change the Shape of the Dataframe

In [ ]:
import pandas as pd
import numpy as np

In [6]:
weather_data = [
    {"date": "2025-05-01", "city": "Kolkata", "temp": 34, "humidity": 78},
    {"date": "2025-05-01", "city": "Bankura", "temp": 41, "humidity": 35},
    {"date": "2025-05-01", "city": "Bhubaneswar", "temp": 36, "humidity": 72},
    {"date": "2025-05-01", "city": "Patna", "temp": 38, "humidity": 40},
    {"date": "2025-05-01", "city": "Ranchi", "temp": 32, "humidity": 55},
    {"date": "2025-05-01", "city": "Darjeeling", "temp": 18, "humidity": 85},
    
    {"date": "2025-05-02", "city": "Kolkata", "temp": 35, "humidity": 80},
    {"date": "2025-05-02", "city": "Bankura", "temp": 42, "humidity": 32},
    {"date": "2025-05-02", "city": "Bhubaneswar", "temp": 37, "humidity": 70},
    {"date": "2025-05-02", "city": "Patna", "temp": 39, "humidity": 38},
    {"date": "2025-05-02", "city": "Ranchi", "temp": 33, "humidity": 52},
    {"date": "2025-05-02", "city": "Darjeeling", "temp": 17, "humidity": 88},
    
    {"date": "2025-05-03", "city": "Kolkata", "temp": 33, "humidity": 82},
    {"date": "2025-05-03", "city": "Bankura", "temp": 40, "humidity": 38},
    {"date": "2025-05-03", "city": "Bhubaneswar", "temp": 35, "humidity": 75},
    {"date": "2025-05-03", "city": "Patna", "temp": 40, "humidity": 35},
    {"date": "2025-05-03", "city": "Ranchi", "temp": 31, "humidity": 58},
    {"date": "2025-05-03", "city": "Darjeeling", "temp": 19, "humidity": 82}
]

In [7]:
# Convert our data to a Pandas Dataframe
df = pd.DataFrame(weather_data)
# Show top 10 values
df.head(10)

         date         city  temp  humidity
0  2025-05-01      Kolkata    34        78
1  2025-05-01      Bankura    41        35
2  2025-05-01  Bhubaneswar    36        72
3  2025-05-01        Patna    38        40
4  2025-05-01       Ranchi    32        55
5  2025-05-01   Darjeeling    18        85
6  2025-05-02      Kolkata    35        80
7  2025-05-02      Bankura    42        32
8  2025-05-02  Bhubaneswar    37        70
9  2025-05-02        Patna    39        38

In [16]:
# Example-1 : Basic Pivoting to change the Shape of the Dataframe
# For Example, If we wanna create Rows with Unique Date values and Columns with Unique City names
df.pivot(index = 'date', columns = 'city')
# As there are 3 unique dates, 3 Rows will be created for each date
# As there are 6 unique City names, 6 unique Subcolumns will be made for the temp and humidity columns.
# There will be a value for each of temp and humidity for an intersection point of date and city.

              temp                                             humidity  \
city       Bankura Bhubaneswar Darjeeling Kolkata Patna Ranchi  Bankura
date
2025-05-01      41          36         18      34    38     32       35
2025-05-02      42          37         17      35    39     33       32
2025-05-03      40          35         19      33    40     31       38


city       Bhubaneswar Darjeeling Kolkata Patna Ranchi
date
2025-05-01          72         85      78    40     55
2025-05-02          70         88      80    38     52
2025-05-03          75         82      82    35     58

In [17]:
# The VALUES parameter
# What if we only need one column, let's say I need only temp data in the output --> Use the
# values = [...column names] to specify which column values you need for each intersection point of 
# date and city
df.pivot(index = "date", columns = "city", values = ['temp'])

              temp
city       Bankura Bhubaneswar Darjeeling Kolkata Patna Ranchi
date
2025-05-01      41          36         18      34    38     32
2025-05-02      42          37         17      35    39     33
2025-05-03      40          35         19      33    40     31